CREATE DATABASE IF NOT EXISTS db;
USE db;

CREATE TABLE IF NOT EXISTS People (
	Id INT NOT NULL AUTO_INCREMENT,
	UserName VARCHAR(255) NOT NULL,
	Email VARCHAR(255) NOT NULL,
	PasswordHash VARCHAR(1024) NOT NULL,
	PasswordSalt VARCHAR(255) NOT NULL,
	PRIMARY KEY (Id)
);

CREATE TABLE IF NOT EXISTS Addresses (
	Id INT NOT NULL AUTO_INCREMENT,
	Street VARCHAR(255) NOT NULL,
	City VARCHAR(255) NOT NULL,
	State VARCHAR(255) NOT NULL,
	Country VARCHAR(255) NOT NULL,
	Zipcode VARCHAR(255) NOT NULL,
	PRIMARY KEY (Id)
);

CREATE TABLE IF NOT EXISTS PersonAddressMap (
	PersonId INT NOT NULL,
	AddressId INT NOT NULL,
	Type VARCHAR(255) NOT NULL,
	PRIMARY KEY (PersonId, AddressId),
	FOREIGN KEY (PersonId) 
		REFERENCES People(Id)
		ON DELETE CASCADE,
	FOREIGN KEY (AddressId) 
		REFERENCES Addresses(Id)
		ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Claims (
	Id INT NOT NULL AUTO_INCREMENT,
	Type VARCHAR(255) NOT NULL,
	Value VARCHAR(255) NOT NULL,
	PersonId INT NOT NULL,
	PRIMARY KEY (Id),
	FOREIGN KEY (PersonId)
		REFERENCES People (Id)
		ON DELETE CASCADE
);