CREATE DATABASE IF NOT EXISTS db;
USE db;

CREATE TABLE People IF NOT EXISTS (
	Id INT NOT NULL AUTO_INCREMENT,
	UserName VARCHAR NOT NULL,
	Email VARCHAR NOT NULL,
	PRIMARY KEY (Id)
);

CREATE TABLE Addresses IF NOT EXISTS (
	Id INT NOT NULL AUTO_INCREMENT,
	Street VARCHAR NOT NULL,
	City VARCHAR NOT NULL,
	State VARCHAR NOT NULL,
	Country VARCHAR NOT NULL,
	Zipcode VARCHAR NOT NULL
	PRIMARY KEY (Id)
);

CREATE TABLE PersonAddressMap IF NOT EXISTS (
	PersonId INT,
	AddressId INT,
	Type VARCHAR,
	PRIMARY KEY (PersonId, AddressId),
	FOREIGN KEY (PersonId) REFERENCES People(Id),
	FOREIGN KEY (AddressId) REFERENCES Addresses(Id)
);